# Use official Python image
FROM python:3.9

# Set working directory
WORKDIR /app

# Copy source files
COPY . .

# Install dependencies
RUN pip install flask psycopg2

# Expose port 8082 for the front-end
EXPOSE 8082

# Run Flask app
CMD ["python", "frontend.py"]
