# Use official Python image
FROM python:3.9

# Set working directory
WORKDIR /app

# Copy source files
COPY . .

# Install dependencies
RUN pip install flask psycopg2

# Expose port
EXPOSE 8082

# Run Flask app with correct port
CMD ["python", "frontend.py"]
